"""CLI interface for CI/CD Quality Gate decision enforcement."""

import argparse
import sys
from pathlib import Path

from judgekit.gate import evaluate_gate_rules


def main():
    parser = argparse.ArgumentParser(
        description="JudgeKit Quality Gate: Hard blocker evaluation for GitHub Actions CI/CD."
    )
    parser.add_argument(
        "diff_report",
        type=str,
        help="Path to diff_report.json generated by comparator.",
    )
    parser.add_argument(
        "--max-faith-drop",
        type=float,
        default=0.02,
        help="Maximum allowed drop in mean faithfulness (default: 0.02).",
    )
    parser.add_argument(
        "--max-critical-regressions",
        type=int,
        default=0,
        help="Maximum allowed critical regressions (default: 0).",
    )
    parser.add_argument(
        "--max-p95-increase-ms",
        type=float,
        default=250.0,
        help="Maximum allowed increase in P95 latency in ms (default: 250.0).",
    )
    args = parser.parse_args()

    report_path = Path(args.diff_report)
    if not report_path.exists():
        print(f"[ERROR] Diff report file not found: {report_path.resolve()}", file=sys.stderr)
        sys.exit(1)

    result = evaluate_gate_rules(
        diff_report_or_path=report_path,
        max_faithfulness_drop=args.max_faith_drop,
        max_critical_regressions=args.max_critical_regressions,
        max_p95_latency_increase_ms=args.max_p95_increase_ms,
    )

    print("=" * 60)
    print("JUDGEKIT: WYNIK BRAMKI JAKOSCI (QUALITY GATE)")
    print("=" * 60)
    print(f"Delta Faithfulness: {result.delta_faithfulness:+.4f}")
    print(f"Delta P95 Latency:  {result.delta_p95_latency_ms:+.2f} ms")
    print(f"Krytyczne regresje: {len(result.critical_regressions)}")
    print("-" * 60)

    if not result.passed:
        for reason in result.failure_reasons:
            print(f"[FAIL] {reason}")
        if result.critical_regressions:
            print("SZCZEGOLY REGRESJI:")
            for r in result.critical_regressions:
                print(
                    f"  - Case {r.get('test_id')}: spadek z {r.get('baseline_score')} do {r.get('candidate_score')}. Powod: {r.get('reason')}"
                )
        print("\n>>> BRAMKA CI ODRZUCILA TEN PULL REQUEST! <<<", file=sys.stderr)
        sys.exit(1)

    print("\n>>> BRAMKA CI ZALICZONA POMYSLNIE <<<")
    sys.exit(0)


if __name__ == "__main__":
    main()
