"""Data contracts and schemas for JudgeKit evaluation pipeline.

Defines schemas for:
- TestCase (Golden Set Input Schema)
- RunOutput & PipelineMetrics (System Execution Schema)
- MetricEvaluation & JudgeReport (Judge Verdict Schema with Chain-of-Thought)
"""

from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class TestCase(BaseModel):
    """Single test case record in the evaluation dataset (Golden Set)."""

    __test__ = False  # Prevent pytest from collecting TestCase as a test class

    id: str = Field(
        ...,
        description="Unique test case identifier (e.g. 'rag-chunk-014' or 'eval-001').",
    )
    category: str = Field(
        ...,
        description="Category of the test case: factual, edge_case, unanswerable, jailbreak, multi_hop, etc.",
    )
    query: str = Field(
        ...,
        description="User query / question posed to the system.",
    )
    expected_behavior: str = Field(
        ...,
        description="Expected behavior directive (e.g. 'Refuse to answer due to missing context').",
    )
    reference_answer: Optional[str] = Field(
        default=None,
        description="Optional ground truth reference answer for factual questions.",
    )
    reference_contexts: Optional[List[str]] = Field(
        default=None,
        description="Optional reference document chunks expected to be retrieved.",
    )


class RunOutput(BaseModel):
    """Execution output from the evaluated system (e.g. RAG pipeline)."""

    test_case_id: str = Field(
        ...,
        description="Identifier referencing the associated TestCase.",
    )
    generated_answer: str = Field(
        ...,
        description="Answer generated by the model/system under evaluation.",
    )
    retrieved_contexts: List[str] = Field(
        default_factory=list,
        description="List of text chunks retrieved and fed into the prompt.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="End-to-end generation latency in milliseconds.",
    )
    tokens_input: int = Field(
        default=0,
        ge=0,
        description="Number of prompt/input tokens consumed.",
    )
    tokens_output: int = Field(
        default=0,
        ge=0,
        description="Number of completion/output tokens generated.",
    )


class MetricEvaluation(BaseModel):
    """Evaluation result for a single metric with mandatory Chain-of-Thought reasoning."""

    reasoning: str = Field(
        ...,
        description="Step-by-step reasoning explaining hallucinations, relevance, or errors before scoring.",
    )
    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized evaluation score between 0.0 and 1.0.",
    )

    @field_validator("reasoning")
    @classmethod
    def reasoning_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Reasoning must not be empty. Chain-of-Thought is required before score.")
        return v


class JudgeReport(BaseModel):
    """Complete verdict produced by the LLM-as-a-Judge system for a given test case."""

    test_case_id: str = Field(
        ...,
        description="Identifier of the evaluated TestCase.",
    )
    faithfulness: MetricEvaluation = Field(
        ...,
        description="Faithfulness metric evaluation (factual grounding in context).",
    )
    answer_relevance: MetricEvaluation = Field(
        ...,
        description="Answer relevance evaluation (addressing the query intent).",
    )
    context_relevance: Optional[MetricEvaluation] = Field(
        default=None,
        description="Optional context relevance evaluation (retrieval quality).",
    )
    safety: MetricEvaluation = Field(
        ...,
        description="Safety evaluation (absence of jailbreaks, toxic or dangerous content).",
    )


class PipelineMetrics(BaseModel):
    """Aggregated run metrics for a single test case execution and evaluation."""

    test_id: str = Field(
        ...,
        description="Identifier of the test case.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="Execution latency in milliseconds.",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Input token count.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Output token count.",
    )
    cost_usd: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated execution cost in USD.",
    )
    faithfulness_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Evaluated faithfulness score (0.0 to 1.0).",
    )
    relevance_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Evaluated answer relevance score (0.0 to 1.0).",
    )
    citation_precision: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Citation precision score (fraction of citations referencing verified sources).",
    )
    refusal_correct: Optional[bool] = Field(
        default=None,
        description="Whether deterministic refusal ('Nie wiem') was correctly applied for out-of-domain/unanswerable query.",
    )
    rubric_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Binary rubric agreement score (e.g. for agent dossier evaluation).",
    )
    stealth_verified: Optional[bool] = Field(
        default=None,
        description="For stealth/adversarial targets, whether UNVERIFIABLE_COMPANY was correctly recognized.",
    )
    budget_compliant: Optional[bool] = Field(
        default=None,
        description="Whether execution stayed strictly within steps and cost budget limits.",
    )
    step_count: Optional[int] = Field(
        default=None,
        description="Execution steps / transitions taken.",
    )
    faithfulness_reasoning: Optional[str] = Field(
        default=None,
        description="Optional detailed faithfulness reasoning.",
    )
    relevance_reasoning: Optional[str] = Field(
        default=None,
        description="Optional detailed answer relevance reasoning.",
    )
    # RAGAS metrics track
    metrics_mode: str = Field(
        default="judge",
        description="Evaluation mode: judge | ragas | both.",
    )
    ragas_faithfulness: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="RAGAS evaluated faithfulness score.",
    )
    ragas_answer_relevancy: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="RAGAS evaluated answer relevancy score.",
    )
    ragas_context_precision: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="RAGAS evaluated context precision score.",
    )
    ragas_context_recall: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="RAGAS evaluated context recall score.",
    )
    ragas_reasoning: Optional[dict] = Field(
        default=None,
        description="RAGAS detailed reasoning per metric.",
    )


class GateConfig(BaseModel):
    """Configuration contract for CI/CD Quality Gate."""

    min_faithfulness: float = Field(default=0.95, description="Minimum acceptable mean faithfulness.")
    min_citation_precision: float = Field(default=0.90, description="Minimum acceptable citation precision.")
    require_deterministic_refusal: bool = Field(default=True, description="Enforce 100% correct refusal on unanswerables.")
    max_faithfulness_drop: float = Field(default=0.02, description="Max allowed regression vs baseline.")
    max_critical_regressions: int = Field(default=0, description="Max allowed drops >= 0.5.")
    max_p95_latency_ms: float = Field(default=2500.0, description="Max absolute P95 latency allowed in ms.")
    max_p95_latency_increase_ms: float = Field(default=250.0, description="Max allowed increase in P95 latency vs baseline.")
    min_rubric_score: float = Field(default=0.83, description="Minimum acceptable binary rubric agreement (e.g. 5/6 = 0.833).")
    require_stealth_zero_hallucination: bool = Field(default=True, description="Require 100% UNVERIFIABLE_COMPANY for phantom entities.")
    max_agent_steps: int = Field(default=12, description="Max execution steps permitted for agent.")
    max_agent_cost_usd: float = Field(default=0.15, description="Max budget in USD permitted for agent.")

    # Optional RAGAS thresholds
    min_ragas_faithfulness: Optional[float] = Field(default=None, description="Minimum acceptable mean RAGAS faithfulness.")
    min_ragas_answer_relevancy: Optional[float] = Field(default=None, description="Minimum acceptable mean RAGAS answer relevancy.")
    min_ragas_context_precision: Optional[float] = Field(default=None, description="Minimum acceptable mean RAGAS context precision.")
    min_ragas_context_recall: Optional[float] = Field(default=None, description="Minimum acceptable mean RAGAS context recall.")
    max_ragas_faithfulness_drop: Optional[float] = Field(default=None, description="Max allowed drop in mean RAGAS faithfulness vs baseline.")

