"""Data contracts and schemas for JudgeKit evaluation pipeline.

Defines schemas for:
- TestCase (Golden Set Input Schema)
- RunOutput & PipelineMetrics (System Execution Schema)
- MetricEvaluation & JudgeReport (Judge Verdict Schema with Chain-of-Thought)
"""

from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class TestCase(BaseModel):
    """Single test case record in the evaluation dataset (Golden Set)."""

    __test__ = False  # Prevent pytest from collecting TestCase as a test class

    id: str = Field(
        ...,
        description="Unique test case identifier (e.g. 'rag-chunk-014' or 'eval-001').",
    )
    category: str = Field(
        ...,
        description="Category of the test case: factual, edge_case, unanswerable, jailbreak, multi_hop, etc.",
    )
    query: str = Field(
        ...,
        description="User query / question posed to the system.",
    )
    expected_behavior: str = Field(
        ...,
        description="Expected behavior directive (e.g. 'Refuse to answer due to missing context').",
    )
    reference_answer: Optional[str] = Field(
        default=None,
        description="Optional ground truth reference answer for factual questions.",
    )
    reference_contexts: Optional[List[str]] = Field(
        default=None,
        description="Optional reference document chunks expected to be retrieved.",
    )


class RunOutput(BaseModel):
    """Execution output from the evaluated system (e.g. RAG pipeline)."""

    test_case_id: str = Field(
        ...,
        description="Identifier referencing the associated TestCase.",
    )
    generated_answer: str = Field(
        ...,
        description="Answer generated by the model/system under evaluation.",
    )
    retrieved_contexts: List[str] = Field(
        default_factory=list,
        description="List of text chunks retrieved and fed into the prompt.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="End-to-end generation latency in milliseconds.",
    )
    tokens_input: int = Field(
        default=0,
        ge=0,
        description="Number of prompt/input tokens consumed.",
    )
    tokens_output: int = Field(
        default=0,
        ge=0,
        description="Number of completion/output tokens generated.",
    )


class MetricEvaluation(BaseModel):
    """Evaluation result for a single metric with mandatory Chain-of-Thought reasoning."""

    reasoning: str = Field(
        ...,
        description="Step-by-step reasoning explaining hallucinations, relevance, or errors before scoring.",
    )
    score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized evaluation score between 0.0 and 1.0.",
    )

    @field_validator("reasoning")
    @classmethod
    def reasoning_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Reasoning must not be empty. Chain-of-Thought is required before score.")
        return v


class JudgeReport(BaseModel):
    """Complete verdict produced by the LLM-as-a-Judge system for a given test case."""

    test_case_id: str = Field(
        ...,
        description="Identifier of the evaluated TestCase.",
    )
    faithfulness: MetricEvaluation = Field(
        ...,
        description="Faithfulness metric evaluation (factual grounding in context).",
    )
    answer_relevance: MetricEvaluation = Field(
        ...,
        description="Answer relevance evaluation (addressing the query intent).",
    )
    context_relevance: Optional[MetricEvaluation] = Field(
        default=None,
        description="Optional context relevance evaluation (retrieval quality).",
    )
    safety: MetricEvaluation = Field(
        ...,
        description="Safety evaluation (absence of jailbreaks, toxic or dangerous content).",
    )


class PipelineMetrics(BaseModel):
    """Aggregated run metrics for a single test case execution and evaluation."""

    test_id: str = Field(
        ...,
        description="Identifier of the test case.",
    )
    latency_ms: float = Field(
        ...,
        ge=0.0,
        description="Execution latency in milliseconds.",
    )
    input_tokens: int = Field(
        default=0,
        ge=0,
        description="Input token count.",
    )
    output_tokens: int = Field(
        default=0,
        ge=0,
        description="Output token count.",
    )
    cost_usd: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated execution cost in USD.",
    )
    faithfulness_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Evaluated faithfulness score (0.0 to 1.0).",
    )
    relevance_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Evaluated answer relevance score (0.0 to 1.0).",
    )
    faithfulness_reasoning: Optional[str] = Field(
        default=None,
        description="Optional detailed faithfulness reasoning.",
    )
    relevance_reasoning: Optional[str] = Field(
        default=None,
        description="Optional detailed answer relevance reasoning.",
    )
